[project]
name = "watch-calibration"
version = "0.0.2"
dependencies = [
]
requires-python = ">=3.8"
authors = [
  {name = "Sabar Dasgupta", email = "s@bardasgupta.com"},
  {name = "Paul Nuyujukian", email = "paul@neural.stanford.edu"},
]
maintainers = [
  {name = "Sabar Dasgupta", email = "s@bardasgupta.com"}
]
description = "Basic example implemeting SHREW."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["reproducibility", "replicability"]
classifiers = [
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://bil.stanford.edu"
Documentation = "https://bil.stanford.edu"
Repository = "https://github.com/bil/watch-calibration"

[project.scripts]
wc-collect-data = "watch_calibration.collect_data:collect_data"

[tool.setuptools]
packages = ["watch_calibration"]
