[project]
name = "watch-calibration"
version = "0.0.2"
dependencies = [
]
requires-python = ">=3.8"
authors = [
  {name = "Sabar Dasgupta", email = "s@bardasgupta.com"},
  {name = "Paul Nuyujukian"},
]
maintainers = [
  {name = "Sabar Dasgupta", email = "s@bardasgupta.com"}
]
description = "An ARTS-compatible example experiment"
readme = "README.md"
license = "GPL-3.0"
license-files = ["LICENSE"]
keywords = ["reproducibility", "archives", "containers", "timestamping"]
classifiers = [
  "Programming Language :: Python"
]

[project.urls]
Repository = "https://github.com/bil/watch-calibration"

[project.scripts]
wc-query-devices = "watch_calibration.collect_data:query_devices"
wc-collect-data = "watch_calibration.collect_data:collect_data"

[tool.setuptools]
packages = ["watch_calibration"]
